# Generated by Django 6.1.1 on 2026-09-21 05:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('source', models.CharField(choices=[('WEBSITE', 'Website'), ('INSTAGRAM', 'Instagram'), ('FACEBOOK', 'Facebook'), ('TIKTOK', 'TikTok'), ('WHATSAPP', 'WhatsApp'), ('MESSENGER', 'Messenger'), ('PHONE', 'Phone'), ('GOOGLE', 'Google'), ('OTHER', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('INTERESTED', 'Interested'), ('NEGOTIATING', 'Negotiating'), ('CONVERTED', 'Converted'), ('LOST', 'Lost')], default='NEW', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('interested_product', models.CharField(blank=True, max_length=200)),
                ('owner_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='customers.customer')),
            ],
        ),
    ]
