# Generated by Django 6.1.1 on 2026-09-21 05:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('PRODUCT_VIEW', 'Product view'), ('PRODUCT_CLICK', 'Product click'), ('ADD_TO_CART', 'Add to cart'), ('PURCHASE', 'Purchase'), ('CUSTOMIZATION_REQUEST', 'Customization request')], max_length=30)),
                ('source', models.CharField(choices=[('WEBSITE', 'Website'), ('INSTAGRAM', 'Instagram'), ('FACEBOOK', 'Facebook'), ('TIKTOK', 'TikTok'), ('WHATSAPP', 'WhatsApp'), ('MESSENGER', 'Messenger'), ('GOOGLE', 'Google'), ('DIRECT', 'Direct'), ('OTHER', 'Other')], default='DIRECT', max_length=20)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='customers.customer')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='catalog.product')),
            ],
        ),
    ]
